apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.fullname | quote }}
  namespace: {{ .Values.namespace | quote }}
data:
 mariadb_root_password: {{ .Values.database.secret.mariadbrootpassword }}
 db_user: {{ .Values.database.secret.user }}
 db_password: {{ .Values.database.secret.userpassword }}
 db_name: {{ .Values.database.secret.dbname }}
type: Opaque