apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.fullname | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    run: {{ .Values.database.service.fullname | quote }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.database.service.port | default 3306 }}
      targetPort: {{ .Values.database.service.port | default 3306 }}
  selector:
    app: mariadb