apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ecom-hpa
spec:
  scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: ecom-web
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10