apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-hpa
spec:
  selector:
    matchLabels:
      run: ecom-hpa
  template:
    metadata:
      labels:
        run: ecom-hpa
    spec:
      containers:
      - name: ecom-hpa
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-svc
  labels:
    run: ecom-svc
spec:
  ports:
  - port: 80
  selector:
    run: ecom-hpa