apiVersion: apps/v1
kind: Deployment
metadata:
 name: ecom-web
 labels:
  app: ecom-web
spec:
 replicas: 1
 selector:
  matchLabels:
   app: ecom-web
 template:
  metadata:
   labels:
    app: ecom-web
  spec:
   imagePullSecrets:
     - name: regcred
   containers:
    - name: ecom-web
      image: tomiwa97/ecom-web:v1
      imagePullPolicy: Always
      ports:
       - containerPort: 80
      env:
       - name: DB_HOST
         valueFrom:
          configMapKeyRef:
           name: ecom-web-configmap
           key: database_url
       - name: DB_USER
         valueFrom:
          secretKeyRef:
           name: mariadb-secret
           key: db_user
       - name: DB_PASSWORD
         valueFrom:
          secretKeyRef:
           name: mariadb-secret
           key: db_password
       - name: DB_NAME
         valueFrom:
          secretKeyRef:
           name: mariadb-secret
           key: db_name
