name: PHP App CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: Run test suite
      run: composer run-script test

 docker:
   needs: build
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile 
        push: false
        tags: ecom-web:v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    -  run: | 
        docker tag ecom-web:v1 ${{ secrets.DOCKERHUB_USERNAME }}/ecom-web:v1 
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecom-web:v1