name: PHP App CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 docker:
   needs: build
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile 
        push: false
        tags: ecom-web:v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    -  run: | 
        docker tag ecom-web:v1 ${{ secrets.DOCKERHUB_USERNAME }}/ecom-web:v1 
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecom-web:v1
