name: PHP App CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: PHP testing
      run: echo "php test"

 docker:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile 
        push: false
        tags: ecom-web:v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    -  run: | 
        docker tag ecom-web:v2 ${{ secrets.DOCKERHUB_USERNAME }}/ecom-web:v2 
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecom-web:v2

 terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          working-directory: ./terraform
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply --auto-approve -no-color
      
      - name: Terraform Destroy
        run: terraform destroy --auto-approve -no-color

 